all_movies = [
    "The Dark Knight",
    "The Godfather",
    "Interstellar",
    "Gladiator",
    "Inception",
    "Django Unchained",
    "Gravity",
    "The Martian",
    "La La Land",
    "The Avengers",
    "Jason Bourne",
    "The Curious Case of Benjamin Button",
    "Fight Club",
    "The Matrix",
    "American Psycho",
    "Alien",
    "Predator",
    "WALL-E",
    "The Shining",
    "Spider-Man",
    "Joker",
    "Toy Story",
    "Passengers",
    "3 Idiots",
    "Star Wars",
    "Up",
    "Licence to Kill",
    "Quantum of Solace",
    "No Time to Die",
    "The Italian Job",
    "Shutter Island",
    "Titanic",
    "Jurassic Park",
    "The Intern",
    "The Shawshank Redemption",
    "Sherlock Holmes",
    "The Wolverine",
]

